#+title: org-transclusion-src-heading: Extension for org-transclusion for outline-mode headings

* Motivation
Highly volatile source files (such as configuration files) make [[https:github.com/nobiot/org-transclusion][org-transclusion's]] line-based transclusion brittle.

I wanted to include some specific sections (but not all!) of my emacs configuration with added commentary on my website, which is deployed with org-mode. I moved away from a literate configuration a long time ago, but missed the nice formatting and publishing capabilities of org-mode. Because my configuration is constantly evolving, the line-based transclusion included in the package would be liable to break if I added/subtracted the configuration or refactored it.

I chose to extend org-transclusion to use a minimal outline-mode based organization of the source file to pull sections into the transclusion with a new =:heading= keyword to the =#+transclude:= directive.
This will pull in the all the text of a specific heading level from your source file into code block.
* Installation
This package is not on MELPA, but many emacs users use package managers with installation from version control systems such as elpaca and straight. Refer to your package manager's documentation to see how this is done.

Those not using such a package manager can clone the repository locally and use =use-package= with the =:load-path= keyword pointing to where the repository is cloned.

Once installed, you must make org-transclusion aware of the extension after it is loaded by placing this line somewhere in your configuration.
#+begin_src emacs-lisp
(org-transclusion-set-extensions
   'org-transclusion-extensions
   (add-to-list 'org-transclusion-extensions 'org-transclusion-src-heading))
#+end_src
This will insert the src-heading functions into the org-transclusion pipeline.
* Usage
*** Basic Usage
To begin transcluding, you really only need the variable =outline-regexp= set in such a way that the characters that determine the level of the outline is matched in capture group number =org-transclusion-src-heading-level-capture-group= and the name of the heading is matched in the group =org-transclusion-src-heading-name-capture-group=.
This is needed to accommodate source languages where single line comments are wrapped in 

We follow the recommendation of the emacs manual that the first two should be set as a buffer-local variable.
As a note, =outline-heading= should be able to correctly calculate the level of your headings.
This likely means you will have to write your own (see below for mine).

*** Batteries-included config example
I provide my own configuration and steps to proceed based on it.
#+begin_src emacs-lisp
(use-package org-transclusion-src-heading
  :config
  ;; Convention: all my buffer-local outline-regexps
  ;; will capture stars to group 1 and the heading name
  ;; to group 2. Design them for your source buffer accordingly
  (setopt org-transclusion-src-heading-level-capture-group 1
          org-transclusion-src-heading-name-capture-group 2)

  (defun my/outline-level ()
    "Determine outline level assuming
`outline-regexp' captures asterisks into
`org-transclusion-src-heading-level-capture-group'."
    (if  (looking-at outline-regexp)
        (length (match-string org-transclusion-src-heading-level-capture-group))
      0))
  ;; Universally use this function to determine outline headings
  (add-hook 'prog-mode-hook :local (setq outline-level #'my/outline-level)))
#+end_src
To begin transcluding for a new source language, do the following:

1. Enter source buffer and run =add-file-local-variable=
2. Set =outline-regexp= to a regex that captures heading level characters (like =*=) to capture group 1
   and the heading name to capture group 2
3. (Optional) Hook this =outline-regexp= value to the major mode to avoid repetition of file local vars
4. Done. You may transclude headings now
*** Example with example config
If you properly capture your asterisks for heading levels, you should write your own function for =outline-level= to compute the outline levels (see below).

#+begin_src emacs-lisp
;;; * fibonacci
(defun fib (n)
  (cond ((eq n 0) 1)
         ((eq n 1) 1)
         (t (+ (fib (1- n)) (fib (- n 2))))))

;;; ** subheading
(message "%s" 'foobar)
;;; * ising
(message "%s" 'super!)

;; Local Variables:
;; outline-regexp: ";;; \\(\\*+\\) \\(.*\\)$"
;; End:

#+end_src

Once these are set, you can transclude into an org file like so:
#+begin_src org
#+transclude: [[file:/path/to/src-file]] :src [src-language] :heading "[heading name]"
#+end_src

For our elisp example, we could transclude the first level 1 heading with
#+begin_src org
#+transclude: [[file:/path/to/src-file]] :src emacs-lisp :heading "fibonacci"
#+end_src

See =examples/= for more examples.
